### ISSUE TITLE
Can you Update the EXE? (Files Original Names)

### ISSUE THREAD

**Issue by Clouddark75** [Un-index/imgBB-bulk-exe#2]
Hey, thanks for the update on the website (really appreciate it) and the npm version. Can you update the exe as well?

Thank you very much for this great tool!

**Comment by Un-index** [comment]
Thanks, I’ll update it for the exe as well soon.

**Comment by deontic** [comment]
Hi, it seems the tool already does this. If it's not setting the filename to the name you set **when you uploaded an image**, please let me know.
